CREATE TABLE IF NOT EXISTS categories (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,
    icon_link VARCHAR(200) NOT NULL,
    description VARCHAR(200) NOT NULL
);